spring:
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/zuizhong?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/zuizhong?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B
    hikari:
      max-lifetime: 500000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath*: /mybatis/**Mapper.xml
server:
  port: 9090